<?php

/**
 * @file
 * Functions to support theming in the Z kufra von theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function zkufravon_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function zkufravon_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function zkufravon_preprocess_node(&$variables) {

}
